# Copyright 2026 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

version: 2

project_name: terramate

builds:
  - id: terramate
    main: ./cmd/terramate
    binary: terramate
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: terramate-ls
    main: ./cmd/terramate-ls
    binary: terramate-ls
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    ids:
      - terramate
      - terramate-ls
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  name_template: >-
    {{ if contains .Tag "-dev." }}Development build {{ .Tag }}{{ else }}{{ .Tag }}{{ end }}
