# Copyright 2024 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

image: golang

clone:
  enabled: true
  depth: full

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'build Terramate'
          script:
            - make build
            - go install github.com/hashicorp/hc-install/cmd/hc-install@latest
            - hc-install install -version 1.6.0 terraform
            - cp ./terraform /usr/local/bin/terraform
            - ./bin/terramate run --changed -- terraform init
            - ./bin/terramate run --changed --target linux-go-packages --parallel 12 -- terraform plan -detailed-exitcode
  branches:
    main:
      - step:
          name: 'build Terramate'
          script:
            - make build
            - go install github.com/hashicorp/hc-install/cmd/hc-install@latest
            - hc-install install -version 1.6.0 terraform
            - cp ./terraform /usr/local/bin/terraform
            - ./bin/terramate run --changed -- terraform init
            - ./bin/terramate run --changed --target linux-go-packages --parallel 12 -- terraform apply
            - ./bin/terramate run --changed --target linux-go-packages -- terraform plan -detailed-exitcode
