# Copyright 2026 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

name: OSS / Build & Test

on:
  workflow_call:

jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # pin@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: make build
        run: make build

      - name: make generate (fail on drift)
        run: make generate && git diff --exit-code

      - name: make test
        run: make test
