# Copyright 2026 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

name: OSS / Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  build_test:
    name: Build and Test
    uses: ./.github/workflows/oss-build-test.yml

  publish_release:
    name: Publish release binaries
    needs: build_test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install: true

      - name: generate release notes
        run: mise exec -- cog changelog --at "${{ github.ref_name }}" > /tmp/notes.md

      - name: Run GoReleaser (release)
        run: mise exec -- goreleaser release --clean --release-notes=/tmp/notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
